# -*- coding: utf-8 -*-
# KXmp is a xm media player for KDE4
 # Copyright (C) 2008, Oğuzhan Eroğlu <rohanrhu2@gmail.com>
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.

 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.

from PyQt4 import QtCore, QtGui
import os
import sys
import locale
import gettext

local, encoding = locale.getdefaultlocale()

_ = gettext.translation("kxmp", fallback=True, languages=[local]).ugettext

class Ui_kxmpWindow(object):
    def setupUi(self, kxmpWindow):
        kxmpWindow.setObjectName("kxmpWindow")
        kxmpWindow.resize(413, 421)
        kxmpWindow.setMaximumSize(QtCore.QSize(1500, 1500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sazli.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        kxmpWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(kxmpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.searchLine = QtGui.QLineEdit(self.centralwidget)
        self.searchLine.setObjectName("searchLine")
        self.gridLayout.addWidget(self.searchLine, 1, 0, 1, 1)
        self.playButton = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/icons/media_playback_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setFlat(False)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 2, 1, 1)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/icons/media_playback_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 1, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listMusics = QtGui.QListWidget(self.groupBox)
        self.listMusics.setAlternatingRowColors(True)
        self.listMusics.setViewMode(QtGui.QListView.ListMode)
        self.listMusics.setBatchSize(100)
        self.listMusics.setObjectName("listMusics")
        self.gridLayout_2.addWidget(self.listMusics, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 4)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 0, 1, 1, 3)
        kxmpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(kxmpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 413, 27))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtGui.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuG_r_n_m = QtGui.QMenu(self.menubar)
        self.menuG_r_n_m.setObjectName("menuG_r_n_m")
        self.menuYard_m = QtGui.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        kxmpWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(kxmpWindow)
        self.statusBar.setObjectName("statusBar")
        kxmpWindow.setStatusBar(self.statusBar)
        self.actionHakk_nda = QtGui.QAction(kxmpWindow)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.actionHelp = QtGui.QAction(kxmpWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/top_buttons/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon3)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(kxmpWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPlay = QtGui.QAction(kxmpWindow)
        self.actionPlay.setIcon(icon1)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtGui.QAction(kxmpWindow)
        self.actionStop.setIcon(icon2)
        self.actionStop.setObjectName("actionStop")
        self.actionExit = QtGui.QAction(kxmpWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/top_buttons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtGui.QAction(kxmpWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/top_buttons/icons/preferences_system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon5)
        self.actionSettings.setObjectName("actionSettings")
        self.actionColor = QtGui.QAction(kxmpWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/top_buttons/icons/palet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon6)
        self.actionColor.setObjectName("actionColor")
        self.menuDosya.addAction(self.actionPlay)
        self.menuDosya.addAction(self.actionStop)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionSettings)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionExit)
        self.menuG_r_n_m.addAction(self.actionColor)
        self.menuYard_m.addAction(self.actionHelp)
        self.menuYard_m.addAction(self.actionAbout)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuG_r_n_m.menuAction())
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(kxmpWindow)
        QtCore.QMetaObject.connectSlotsByName(kxmpWindow)

    def retranslateUi(self, kxmpWindow):
        kxmpWindow.setWindowTitle(_(u"KXmp xm Player"))
        self.searchLine.setStatusTip(_(u"Search music..."))
        self.playButton.setStatusTip(_(u"Play music..."))
        self.playButton.setText(_(u"Play"))
        self.stopButton.setStatusTip(_(u"Stop music..."))
        self.stopButton.setText(_(u"Stop"))
        self.groupBox.setTitle(_(u"Musics"))
        self.label.setText(_(u"Search:"))
        self.menuDosya.setTitle(_(u"File"))
        self.menuG_r_n_m.setTitle(_(u"Tools"))
        self.menuYard_m.setTitle(_(u"Help"))
        self.actionHakk_nda.setText(_(u"Hakkında"))
        self.actionHelp.setText(_(u"Help"))
        self.actionHelp.setStatusTip(_(u"Help for KXmp"))
        self.actionAbout.setText(_(u"About KXmp"))
        self.actionAbout.setStatusTip(_(u"About for KXmp"))
        self.actionPlay.setText(_(u"Play"))
        self.actionPlay.setStatusTip(_(u"Play music..."))
        self.actionStop.setText(_(u"Stop"))
        self.actionStop.setStatusTip(_(u"Stop music..."))
        self.actionExit.setText(_(u"Exit"))
        self.actionExit.setStatusTip(_(u"Exit"))
        self.actionSettings.setText(_(u"Settings"))
        self.actionSettings.setStatusTip(_(u"Application settings..."))
        self.actionColor.setText(_(u"Colors"))
        self.actionColor.setStatusTip(_(u"Colored list..."))

import kxmpicons_rc
